name: Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [9.*, 10.*, 11.*]
        include:
          - laravel: 9.*
            testbench: 7.*
            pest: 2.*
          - laravel: 10.*
            testbench: 8.*
            pest: 2.*
          - laravel: 11.*
            testbench: 9.*
            pest: 2.*
          - laravel: 8.*
            testbench: 6.*
            pest: 1.*
        exclude:
          - laravel: 11.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ matrix.laravel }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php }}-${{ matrix.laravel }}-
            ${{ runner.os }}-composer-${{ matrix.php }}-
            ${{ runner.os }}-composer-

      - name: Cache vendor directory
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ matrix.php }}-${{ matrix.laravel }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-vendor-${{ matrix.php }}-${{ matrix.laravel }}-
            ${{ runner.os }}-vendor-${{ matrix.php }}-
            ${{ runner.os }}-vendor-

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --optimize-autoloader

      - name: Cache PHPUnit result cache
        uses: actions/cache@v4
        with:
          path: |
            .phpunit.result.cache
            build/
          key: ${{ runner.os }}-phpunit-${{ matrix.php }}-${{ matrix.laravel }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-phpunit-${{ matrix.php }}-${{ matrix.laravel }}-
            ${{ runner.os }}-phpunit-${{ matrix.php }}-
            ${{ runner.os }}-phpunit-

      - name: Create build directory
        run: mkdir -p build

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest --parallel
