name: Tests Laravel 9

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test-laravel-9:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2]

    name: PHP ${{ matrix.php }} - Laravel 9.*

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-laravel9-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php }}-laravel9-
            ${{ runner.os }}-composer-${{ matrix.php }}-
            ${{ runner.os }}-composer-

      - name: Cache vendor directory
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ matrix.php }}-laravel9-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-vendor-${{ matrix.php }}-laravel9-
            ${{ runner.os }}-vendor-${{ matrix.php }}-
            ${{ runner.os }}-vendor-

      - name: Install dependencies
        run: |
          composer require "laravel/framework:^9.0" "orchestra/testbench:^7.0" "pestphp/pest:^1.0|^2.0" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --optimize-autoloader

      - name: Cache PHPUnit result cache
        uses: actions/cache@v4
        with:
          path: |
            .phpunit.result.cache
            build/
          key: ${{ runner.os }}-phpunit-${{ matrix.php }}-laravel9-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-phpunit-${{ matrix.php }}-laravel9-
            ${{ runner.os }}-phpunit-${{ matrix.php }}-
            ${{ runner.os }}-phpunit-

      - name: Create build directory
        run: mkdir -p build

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest
